config:
    AZURE_SUBSCRIPTION_ID: "f6ce1e2a-5984-4caf-a25c-b84249640c08" # Please modify to your subscription
    AZURE_RESOURCE_GROUP: "aml-automl-handson" # Please modify to your Azure resource group
    AZURE_WORKSPACE: "aml-automl-handson-aml" # Please modify to your Azure workspace
    AZURE_DATA_NAME: "in-car-copilot-fn-temperature-data" # Please modify to your AzureML data name
    DATA_DIR: "./dataset"
    CLOUD_DIR: "./cloud"
    HF_MODEL_NAME_OR_PATH: "microsoft/Phi-3.5-mini-instruct"
    IS_DEBUG: true
    USE_LOWPRIORITY_VM: false

train:
    azure_env_name: "llm-finetuning-2024-11-05" # Please modify to your AzureML env name
    azure_compute_cluster_name: "gpu-cluster-nc-a100"
    azure_compute_cluster_size: "Standard_NC24ads_A100_v4" # 1 x A100 (80GB)
    epoch: 1
    train_batch_size: 1
    eval_batch_size: 1
    model_dir: "./outputs"
    wandb_api_key: ""
    wandb_project: ""
    wandb_run_name: ""

serve:
    azure_env_name: "llm-serving-2024-11-05" # Please modify to your AzureML env name
    azure_model_name: "in-car-copilot-fn-temperature-model" # Please modify to your AzureML model name
    azure_endpoint_name: "in-car-copilot-fn-temperature"
    azure_deployment_name: "phi3-blue"
    azure_serving_cluster_size: "Standard_NC6s_v3"
